### ISSUE TITLE
Failing to use nix with flakes enabled with GitHub Actions

### ISSUE THREAD

**Issue by staticdev** [Ableton/ansible-role-nix#146]
I am trying to integrate this role in my [workspace playbook](https://github.com/staticdev/linux-workstation-playbook) but I am having trouble trying to run nix after running the role.

I created a repo with minimal way to reproduce https://github.com/staticdev/nix-playbook/pull/1.

I have this error on molecule as well as on Debian machines. I see everything was created, I add the `.nix-profile/bin` to path but still `nix profile install` fails with missing flakes config.

Any idea what might be the cause?

**Comment by nre-ableton** [comment]
Hi @staticdev, can you please provide a logfile of running the playbook (preferably with `-v`)? Thanks!

**Comment by nre-ableton** [comment]
@staticdev Ok. I'm not terribly familiar with Vagrant and haven't tested this role there, so I'm not sure I can easily reproduce. But if you can provide another error log, that would be much appreciated.

**Comment by staticdev** [comment]
@nre-ableton it is a bit complex but basically the tests for my playbook were relying on root user, the approach you use in this role is much better. Actually I will try to use as an inspiration for improving the playbook. So the error fundamentally comes from my side. Sorry for the inconvenience.

**Comment by nre-ableton** [comment]
@staticdev No problem! Glad that you managed to sort it out. :+1:

**Comment by staticdev** [comment]
Sorry to bother again @nre-ableton but actually I did not sort it out. I have made a repository with minimal reproduction:
https://github.com/staticdev/nix-playbook

Also the output -v is in there: https://github.com/staticdev/nix-playbook/blob/main/output.txt

**Comment by nre-ableton** [comment]
Hi @staticdev,
So I think that the problem here is probably related to running your playbook as `root`. There are a few things that I noticed in the build log. First, whenever `ableton.nix` is creating files/directories they are owned by the root group (GID 0). This is probably not ideal and we should consider providing a `nix_group` variable to the role.

However, the role itself executes fine. It's the package installation task that fails. I would recommend forcing this task to run as the `workspace_user`. In other words, try this:

```yaml
    - name: "Install nix package kubectl"
      become: true
      become_user: "{{ workspace_user }}"
      ansible.builtin.command: "nix-env -iA nixpkgs.kubectl"
      environment:
        PATH: "{{ workspace_user_details.home + '/.nix-profile/bin:$PATH' }}"
      changed_when: true
```

Also it's worth noting that `"warning: the group 'nixbld' specified in 'build-users-group' does not exist` produced some interesting search results on the internet. Here's some other links that may be useful:

- https://github.com/NixOS/nix/issues/3337
- https://cardano.stackexchange.com/questions/6231/error-when-installing-nix-the-group-nixbld-specified-in-build-users-group
- https://github.com/NixOS/nix/issues/1559
- https://github.com/LnL7/nix-docker/issues/9
- https://github.com/NixOS/nix/issues/4219

There are some other search results as well, but I only linked the most interesting (IMHO) ones that I found. Most of these threads mention stuff about running the nix install script as root (which `ableton.nix` does not do), but that leads me to believe that doing other nix stuff as the root user could be problematic.

**Comment by staticdev** [comment]
> 

Thanks for your answer @nre-ableton! Actually I've been trying without success for find an straightforward way to run ansible playbooks on molecule without being root. It is the default and hard to change.

I know it is possible to change molecule.yml to have:

```
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_user: ansible
```

Then, gather facts does not work. You disable it, many roles stop work.. it is really not trivial, but would be the best to enforce good level of security starting from the tests. I will continue trying... about this group error I will also investigate later once I have the running user part smooth.

**Comment by staticdev** [comment]
@nre-ableton I found a better way to execute the playbook unprivileged https://github.com/staticdev/nix-playbook/commit/ae326ace4779855abab9b8b614f9c07000376907
Still would be nice if when we execute `ableton.nix` it adds `$HOME/.nix-profile/bin` to $PATH, so that every user of the role do not have to figure out how to do it.

**Comment by nre-ableton** [comment]
Hmm, that would be nice, but I'm not sure that it's possible. So I just tried the following playbook:

```yaml
---
- name: Run test task
  hosts: localhost

  tasks:
   - debug:
        msg: "HI THERE {{ ansible_env.PATH }}"
    - set_fact:
        ansible_env.PATH: "{{ ansible_env.PATH }}:/foo/bar"
    - debug:
        msg: "HI THERE {{ ansible_env.PATH }}"
```

The second `debug` task is not reached, because `set_fact` fails:

> `The variable name 'ansible_env.PATH' is not valid. Variables must start with a letter or underscore character, and contain only letters, numbers and underscores.`

(Same goes for `ansible_env["PATH"]`). However, we can update the documentation and advise users on how to set the `PATH` on either a task or playbook level. For example, in your playbook you could add this section to the top:

```yaml
environment:
  PATH: "{{ ansible_user_home }}/.nix-profile/bin:{{ ansible_env.PATH }}"
```

...and that *should* work fine once Nix is installed. Would this be a good solution?

**Comment by staticdev** [comment]
@nre-ableton this should solve your problem:

```yaml
---
- name: Run test task
  hosts: localhost

  tasks:
   - debug:
        msg: "HI THERE {{ ansible_env.PATH }}"
   - name: Add Nix to PATH
     ansible.builtin.set_fact:
       ansible_env: "{{ ansible_env | combine({'PATH': ansible_env.HOME + '/.nix-profile/bin:' + ansible_env.PATH}) }}"
    - debug:
        msg: "HI THERE {{ ansible_env.PATH }}"
```

**Comment by nre-ableton** [comment]
@staticdev Interesting. That does work, but unfortunately in practice, it's not enough to run further Nix commands via Ansible. Despite the `PATH` being set correctly, Ansible still complains that it can't find `nix-env` and other such binaries.

However, I think I have a much simpler solution. Since the Nix installer already modifies `~/.profile`, you just need to add `become_flags: "--login"` to such commands. I pushed a WIP commit, and you can see what that looks like for this project's Molecule configuration here: https://github.com/Ableton/ansible-role-nix/compare/nre/main/nix-binary-path?expand=1

To save you a click, it looks something like this:

```yaml
    - name: Try to install a Nix package
      become: true
      become_flags: "--login"
      become_user: "{{ nix_user }}"
      shell: "nix-env -i hello"
      when: "'hello' not in nix_packages.stdout"
```

I'm not super wild about using `shell` (and neither is ansible-lint for that matter), but IMHO it's a lot less ugly than setting an `environment` property for such tasks. What do you think about this solution?

**Comment by staticdev** [comment]
@nre-ableton I will try if this is possible but now I changed the whole playbook to connect a non-privileged from the start. I updated the playbook example that just installs kubectl: https://github.com/staticdev/nix-playbook.

I also started using `nix_flakes: true`. For some reason it is enabling but when I run the command `nix profile install` it complains it is not enabled. I created a separate branch for that running molecule on Github Actions with -v: https://github.com/staticdev/nix-playbook/pull/1

**Comment by nre-ableton** [comment]
Sorry for the late reply, I've been busy with some other stuff these days. Looking at the log, the exact cause of the error seems to be:

> `error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override`

We are definitely setting that feature, but in `~/.config/nix.conf`. Looking at your playbook, I see that you are running as a non-root user so it *should* work. I have a few ideas:

- Try running `command: nix-env -i kubectl`. This seems to be a canonical package, why do you need to use a flake for it?
- Use `shell` instead of `command` with the `--login` option (as we talked about previously).
- We could also consider writing the flake configuration to `/etc/nix/nix.conf` as [suggested here](https://cardano.stackexchange.com/a/6686/9661). I guess that is for multi-user installations, but maybe it would be smart to write to both files.

**Comment by staticdev** [comment]
Answering in points to your questions:

- This repository I created is just an example to show the issue. I used `kubectl` randomly but in fact could be any package.
- It also tried `shell` even combined with `--login`, no difference it still complains about `error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override` and this happens only when I run molecule on **Github Actions not locally**! This is a total mystery for me now, maybe I can try to interact also in some molecule channel to try to ask for extra help.

**Comment by nre-ableton** [comment]
Interesting, I'll try to mess around with this a bit more today and hopefully figure out what's going on.

**Comment by staticdev** [comment]
@nre-ableton I spent many hours on this problem and tried many different ansible/molecule settings or changes in my playbook but the problem was not there! The fact was: always tests passed locally for me and never passed on GitHub Actions. I discovered the reason is: nix-user path is a fallback path not the default! In my test machine I do not have a XDG_CONFIG_HOME set, so it works. But GitHub Actions sets it, when I force it to unset everything works!

I do not understand the reason behind relying in this variable for installation of nix if you need a clearly defined nix-user to have it installed. Could you explain if that is intentional and why? Maybe I am missing something, but in case you have a different user name for XDG_CONFIG_HOME and nix-user you can even have inconsistent behavior of which path is used on different tasks.

**Comment by nre-ableton** [comment]
@staticdev Thanks for your detailed investigation! And also, sorry for not getting back to this issue sooner, I was quite busy last week.

At first I was a bit puzzled as to what causes this error, because the logic in `tasks/main.yml` seems pretty sound:

1. Use `XDG_CONFIG_DIR` if it is defined
2. If it isn't defined, then fall back to a sane default (`~/.config`)

However, if I understand correctly, the problem comes from when `XDG_CONFIG_DIR` _is defined_, but `nix_user` isn't the same as the user running the playbook. In this case, the value would be used, but it points to a directory that the Nix user doesn't have permission to access.

Maybe a better solution is to harden these conditions, like so:

```yaml
- name: Set fact for XDG user config dir
  ansible.builtin.set_fact:
    xdg_user_config_dir: "{{ lookup('env', 'XDG_CONFIG_HOME') }}"
  when: nix_user == lookup('env', 'USER')

# The lookup module does have a default parameter, but we can't use Jinja2 templates there
- name: Use fallback default for XDG user config dir
  ansible.builtin.set_fact:
    xdg_user_config_dir: "{{ nix_user_details.home }}/.config"
  when: xdg_user_config_dir is not defined
```

What do you think about this?

**Comment by staticdev** [comment]
Thanks a lot, I have seen it. I just don't understand why `XDG_CONFIG_HOME` is the default not the fallback. But sure I will test, let's find a possible way to do it.

**Comment by nre-ableton** [comment]
> Thanks a lot, I have seen it. I just don't understand why `XDG_CONFIG_HOME` is the default not the fallback. But sure I will test, let's find a possible way to do it.

It's the default because Nix looks at these environment variables if defined (see https://github.com/NixOS/nix/issues/1079). This was implemented in https://github.com/Ableton/ansible-role-nix/pull/67, which was submitted by a third-party. You can read the details in that PR thread, but basically it was originally submitted with a `TODO: proper XDG compliance...` comment, which was reworked to actually look at the environment variables. It's been the default since then, for better or worse.
